# Generated by Django 3.2.6 on 2022-07-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='screenshot',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
