# Generated by Django 3.2.6 on 2022-07-13 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0004_alter_userinfo_user_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='userI',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='prikol.userinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_task',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='prikol.usertask'),
        ),
    ]
