# Generated by Django 3.2.6 on 2022-07-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0005_auto_20220713_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_task',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='lang_code',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='userI',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='prikol.userinfo'),
        ),
    ]
