# Generated by Django 3.2.6 on 2022-07-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0006_auto_20220713_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='force_check',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='usertask',
            name='userImage',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='prikol.usertask'),
        ),
    ]
