# Generated by Django 3.2.6 on 2022-07-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0007_auto_20220714_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='userImage',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='prikol.userimage'),
        ),
    ]
