# Generated by Django 3.2.6 on 2022-07-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0008_alter_usertask_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='count_tasks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
