# Generated by Django 3.2.6 on 2022-07-18 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0009_userinfo_count_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('min_withdrawal', models.IntegerField()),
                ('speed', models.CharField(max_length=16)),
                ('regex', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('example', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.FloatField()),
                ('rub_outcome', models.FloatField(blank=True, default=None, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmation_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(default='New', max_length=120)),
                ('payment_method', models.CharField(default='Crypto', max_length=60)),
                ('wallet_info', models.CharField(blank=True, default=None, max_length=4096, null=True)),
                ('payout_id', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('is_take_into_account', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prikol.userinfo')),
            ],
        ),
    ]
