# Generated by Django 3.2.6 on 2022-07-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0010_withdrawal_withdrawalmethods'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='prev_func',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
