# Generated by Django 3.2.6 on 2022-07-20 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0011_userinfo_prev_func'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pocket_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prikol.withdrawalmethods'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='outcome',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
