# Generated by Django 3.2.6 on 2022-07-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0012_auto_20220720_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='withdrawal_method',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
