# Generated by Django 3.2.6 on 2022-07-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0014_auto_20220722_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcategory',
            old_name='name',
            new_name='en_name',
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='ru_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
