# Generated by Django 3.2.6 on 2022-07-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0015_auto_20220722_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='user',
            new_name='userI',
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='category_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name_category',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='prikol.accounts'),
        ),
    ]
