# Generated by Django 3.2.6 on 2022-07-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0016_auto_20220722_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='lang_code',
            field=models.CharField(blank=True, default='en', max_length=2, null=True),
        ),
    ]
