# Generated by Django 3.2.6 on 2022-07-25 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0017_alter_userinfo_lang_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='prikol.taskcategory'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='current_task',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='prikol.usertask'),
        ),
    ]
