# Generated by Django 3.2.6 on 2022-07-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='User_Image',
        ),
    ]
