# Generated by Django 3.2.6 on 2022-07-13 10:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0002_alter_userimage_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('task_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('link', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('social_network', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('action', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('reward', models.FloatField(blank=True, default=None, null=True)),
                ('comment_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('comment_text', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('comment_username', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='userimage',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='prikol.usertask'),
        ),
    ]
