# Generated by Django 3.2.6 on 2022-07-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prikol', '0003_auto_20220713_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='prikol.usertask'),
        ),
    ]
